version: '3.8'

services:
  java-app:
    build: .
    container_name: java-app
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/data/storage.sqlite
    restart: unless-stopped
